name: dev-release
on:
  push:
    branches:
      - dev
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  push-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Manage cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: go test -v ./...

      - name: Create build directory
        run: mkdir -p installer-contents

      - name: Build cross compilation binary
        run: make cross

      - name: Copy contents to be ported to s3
        run: mv bin/* beeta-agent.service beeta-agent-installer.sh beeta-agent-uninstaller.sh ./installer-contents

      - name: Directory to installer-contents
        run: ls -la ./installer-contents

      - name: Release Binary to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: beeta-agent-dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
          SOURCE_DIR: ./installer-contents
