name: dev-release
on:
  push:
    branches:
      - dev
jobs:
  push-to-artifactory:
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build cross compilation binary
        run: make cross

      - name: Archive dev artifacts for linux amd64
        uses: actions/upload-artifact@v3
        with:
            name: beeta-agent-linux-amd64
            path: bin/beeta-agent-linux-amd64

      - name: Archive dev artifacts for linux arm64
        uses: actions/upload-artifact@v3
        with:
            name: beeta-agent-linux-arm64
            path: bin/beeta-agent-linux-arm64
    
      - name: Archive dev artifacts for linux arm
        uses: actions/upload-artifact@v3
        with:
            name: beeta-agent-linux-arm
            path: bin/beeta-agent-linux-arm