name: dev-release
on:
  push:
    branches:
      - dev
jobs:
  push-to-artifactory:
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create build directory
        run: mkdir -p installer-contents

      - name: Build cross compilation binary
        run: make cross


      - name: Archive dev artifacts for release from bin directory
        uses: actions/upload-artifact@v3
        with: 
          name: dev-artifacts
          path: bin
          